ConnectionError occurred at 19/02/2024, 15:36:03 - HTTPSConnectionPool(host='api.coinmarketcap.com', port=443): Max retries exceeded with url: /data-api/v3/cryptocurrency/listing?start=1&limit=100&sortBy=market_cap&sortType=desc&cryptoType=all&tagType=all&audited=false (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001DCC805B9E0>: Failed to resolve 'api.coinmarketcap.com' ([Errno 11001] getaddrinfo failed)"))
